import type { AppendManagedBlockOperation, ManagedBlockMarker } from "./operations";
import { makeOperationId } from "./operations";

export const GITIGNORE_MANAGED_BLOCK_MARKER = "repo-harness generated-runtime";

export const LEGACY_GITIGNORE_MANAGED_MARKERS: readonly ManagedBlockMarker[] = [
  {
    begin: "# BEGIN: claude-runtime-temp (managed by repo-harness)",
    end: "# END: claude-runtime-temp",
  },
  {
    begin: "# BEGIN: claude-runtime-temp (managed by project-initializer)",
    end: "# END: claude-runtime-temp",
  },
];

export const GITIGNORE_MANAGED_BLOCK_CONTENT = [
  "# Project-specific",
  "artifacts/",
  "coverage/",
  "*.tar.gz",
  "*.tgz",
  "",
  "# External references",
  "_ref/",
  ".codegraph/",
  "",
  "# Local operations state",
  "_ops/",
  "",
  "# Environment",
  ".env",
  ".env.*",
  "!.env.example",
  "",
  "# OS metadata",
  ".DS_Store",
  "",
  "# Runtime evidence and local agent state",
  ".claude/settings.local.json",
  ".claude/.atomic_pending",
  ".claude/.session-id",
  ".claude/.trace.jsonl",
  ".claude/.session-handoff.md",
  ".claude/.task-state.json",
  ".claude/.task-handoff.md",
  ".claude/.codegraph-state/",
  ".claude/*.tmp",
  ".claude/*.bak",
  ".claude/*.bak.*",
  ".claude/*.backup-*",
  "tasks/.current.md.tmp.*",
  ".ai/harness/checks/latest.json",
  ".ai/harness/checks/post-bash-latest.json",
  ".ai/harness/events.jsonl",
  ".ai/harness/archive/",
  ".ai/harness/failures/latest.jsonl",
  ".ai/harness/handoff/current.md",
  ".ai/harness/handoff/resume.md",
  ".ai/harness/capability-context/",
  ".ai/harness/security/*",
  "!.ai/harness/security/.gitkeep",
  ".ai/harness/planning/*",
  "!.ai/harness/planning/.gitkeep",
  ".ai/harness/architecture/events.jsonl",
  ".ai/harness/active-plan",
  ".ai/harness/active-worktree",
  ".ai/harness/sprint/",
  ".ai/harness/worktrees/",
  ".ai/harness/runs/",
  ".ai/harness/triage/*",
  "!.ai/harness/triage/.gitkeep",
  ".codex/*",
  ".claude/.active-plan",
  ".claude/.plan-state/",
].join("\n");

export function gitignoreManagedBlockOperation(status: AppendManagedBlockOperation["status"]): AppendManagedBlockOperation {
  return {
    id: makeOperationId("appendManagedBlock", ".gitignore", GITIGNORE_MANAGED_BLOCK_MARKER),
    kind: "appendManagedBlock",
    path: ".gitignore",
    marker: GITIGNORE_MANAGED_BLOCK_MARKER,
    content: GITIGNORE_MANAGED_BLOCK_CONTENT,
    legacyMarkers: LEGACY_GITIGNORE_MANAGED_MARKERS,
    reason: "Ensure repo-harness generated/runtime ignore block is present and current",
    risk: "low",
    status,
  };
}
